import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import App from "./App";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<App>
			<html lang="en" className="text-[#eee]">
				<body className={inter.className}>
					<main className=" flex bg-[#00ADB5] w-screen h-screen overflow-hidden">
						<Navbar />
						<div className="w-full h-full shadow-left-side rounded-l-3xl md:rounded-l-[4rem] ml-2 p-3 md:p-5 bg-gradient-radial relative">
							{children}
						</div>
					</main>
				</body>
			</html>
		</App>
	);
}
